# Generated by Django 2.2.4 on 2019-09-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='last_hub_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
